CREATE TABLE session (
	token CHAR(64) NOT NULL,
	site_id CHAR(64) NOT NULL,
	user_code CHAR(11) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expires_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (token),
	CONSTRAINT FK_session_site FOREIGN KEY (site_id) REFERENCES site (client_id) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT FK_session_user FOREIGN KEY (user_code) REFERENCES user (code) ON UPDATE CASCADE ON DELETE CASCADE
);